package de.saxsys.android.projectiler.app.generatedmodel;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import de.saxsys.android.projectiler.app.generatedmodel.Track;
import de.saxsys.android.projectiler.app.generatedmodel.Comment;

import de.saxsys.android.projectiler.app.generatedmodel.TrackDao;
import de.saxsys.android.projectiler.app.generatedmodel.CommentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig trackDaoConfig;
    private final DaoConfig commentDaoConfig;

    private final TrackDao trackDao;
    private final CommentDao commentDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        trackDaoConfig = daoConfigMap.get(TrackDao.class).clone();
        trackDaoConfig.initIdentityScope(type);

        commentDaoConfig = daoConfigMap.get(CommentDao.class).clone();
        commentDaoConfig.initIdentityScope(type);

        trackDao = new TrackDao(trackDaoConfig, this);
        commentDao = new CommentDao(commentDaoConfig, this);

        registerDao(Track.class, trackDao);
        registerDao(Comment.class, commentDao);
    }
    
    public void clear() {
        trackDaoConfig.getIdentityScope().clear();
        commentDaoConfig.getIdentityScope().clear();
    }

    public TrackDao getTrackDao() {
        return trackDao;
    }

    public CommentDao getCommentDao() {
        return commentDao;
    }

}
