package de.saxsys.android.projectiler.app.generatedmodel;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import de.saxsys.android.projectiler.app.generatedmodel.Track;

import de.saxsys.android.projectiler.app.generatedmodel.TrackDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig trackDaoConfig;

    private final TrackDao trackDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        trackDaoConfig = daoConfigMap.get(TrackDao.class).clone();
        trackDaoConfig.initIdentityScope(type);

        trackDao = new TrackDao(trackDaoConfig, this);

        registerDao(Track.class, trackDao);
    }
    
    public void clear() {
        trackDaoConfig.getIdentityScope().clear();
    }

    public TrackDao getTrackDao() {
        return trackDao;
    }

}
